//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button PageChange1;
		
		protected System.Web.UI.WebControls.Button PageChange2;
		
		protected System.Web.UI.WebControls.Button PageChange3;
		
		protected System.Web.UI.WebControls.Button PageChange4;
		
		protected System.Web.UI.WebControls.Button PageChange5;
		
		protected System.Web.UI.WebControls.TextBox textInput;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Label blah;
		
		protected System.Web.UI.WebControls.DropDownList GreetList;
		
		protected System.Web.UI.WebControls.Label blahblah;
	}
}
