//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp {
	
	
	public partial class School {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button PageChange1;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.WebControls.TextBox CourseTB;
		
		protected System.Web.UI.WebControls.Button AddButton;
		
		protected System.Web.UI.WebControls.Button DeleteButton;
		
		protected System.Web.UI.WebControls.Button EditButton;
		
		protected System.Web.UI.WebControls.Label AlertLabel;
	}
}
